### ISSUE TITLE
Website Scraping Skills

### ISSUE THREAD

**Issue by shionguha** [marquettecomputationalsocialscience/seniordesign1819#1]
Basic ToDo for demo-ing website scraping skills

**Comment by shionguha** [comment]
Requirements:
1. Write codefile to demonstrate website scraping.
1. Each person forks their own version of the project and submits a pull request for evaluation of code and process.

**Comment by shionguha** [comment]
1/6 pull requests received. I'd like to see each of you sending me pull requests about your code to collect data.

**Comment by shionguha** [comment]
5/6 pull requests received. I think I am missing Bria?

**Comment by bpowell21** [comment]
It says it’s on there, but for some reason it says it’s closed.

On Sep 12, 2018, at 12:32 AM, Shion <notifications@github.com<mailto:notifications@github.com>> wrote:


5/6 pull requests received. I think I am missing Bria?
